Feature/chat
dkumankumah/Edugram pull request #18
Opened 2022-12-23 10:44 UTC by alperenkavakli

List of chats doesn't disappear anymore when choosing a chat. Now the chat application needs to be integrated with the rest of the app.

2022-12-23 11:49 UTC, salmantln approved these changes

2022-12-29 15:54 UTC, dkumankumah requested changes

2022-12-29 15:54 UTC, dkumankumah commented on src/pages/index.tsx
> +        </Flex>
Je vergeet in index </> te sluiten zet het na regel 51

2022-12-29 16:04 UTC, dkumankumah approved these changes

2022-12-29 16:15 UTC, merged